export const productsTest = [
  {
    id: 1,
    img: '../donnacalzados/assets/products/force-adulto-rosanegro.png',
    price: 10500,
    size: ['35', '36', '37', '38', '39', '40'],
    color: ['Blanco', 'Negro', 'Rosa'],
    model: 'Force',
  },
  {
    id: 2,
    img: '../donnacalzados/assets/products/force-adulto-rosablanco.png',
    price: 10500,
    size: ['35', '36', '37', '38', '39', '40'],
    color: ['Blanco', 'Rosa'],
    model: 'Force',
  },
  {
    id: 3,
    img: '../donnacalzados/assets/products/force-adulto-violetablanco.png',
    price: 10500,
    size: ['35', '36', '37', '38', '39', '40'],
    color: ['Blanco', 'Violeta'],
    model: 'Force',
  },

  {
    id: 4,
    img: '../donnacalzados/assets/products/force-adulto-camaleon.png',
    price: 10500,
    size: ['35', '36', '37', '38', '39', '40'],
    color: ['Blanco', 'Violeta', 'Turqueza', 'Amarillo'],
    model: 'Force',
  },
  {
    id: 5,
    img: '../donnacalzados/assets/products/force-engomado-adulto-verdeblanco.png',
    price: 14000,
    size: ['35', '36', '37', '38', '39', '40'],
    color: ['Blanco', 'Turqueza'],
    model: 'Force Engomado',
  },
  {
    id: 6,
    img: '../donnacalzados/assets/products/force-er-adulto-blancorosa.png',
    price: 13500,
    size: ['35', '36', '37', '38', '39', '40'],
    color: ['Blanco', 'Rosa'],
    model: 'Force ER',
  },
  {
    id: 7,
    img: '../donnacalzados/assets/products/force-adulto-blanco.png',
    price: 10500,
    size: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44'],
    color: ['Blanco'],
    model: 'Force',
  },

  {
    id: 8,
    img: '../donnacalzados/assets/products/force-adulto-blanconegro.png',
    price: 10500,
    size: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44'],
    color: ['Blanco', 'Negro'],
    model: 'Force',
  },

  {
    id: 9,
    img: '../donnacalzados/assets/products/force-adulto-negro.png',
    price: 10500,
    size: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44'],
    color: ['Negro'],
    model: 'Force',
  },
  {
    id: 10,
    img: '../donnacalzados/assets/products/force-adulto-negroblanco.png',
    price: 10500,
    size: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44'],
    color: ['Blanco', 'Negro'],
    model: 'Force',
  },

  {
    id: 11,
    img: '../donnacalzados/assets/products/force-engomado-adulto-azulnegro.png',
    price: 14000,
    size: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44'],
    color: ['Blanco', 'Negro', 'Azul'],
    model: 'Force Engomado',
  },
  {
    id: 12,
    img: '../donnacalzados/assets/products/force-engomado-adulto-blanconegro.png',
    price: 14000,
    size: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44'],
    color: ['Blanco', 'Negro'],
    model: 'Force Engomado',
  },

  {
    id: 13,
    img: '../donnacalzados/assets/products/force-justdoit-adulto-negroblanco.png',
    price: 14000,
    size: ['35', '36', '37', '38', '39', '40'],
    color: ['Blanco', 'Negro', 'Naranja'],
    model: 'Force Just Do It',
  },
  {
    id: 14,
    img: '../donnacalzados/assets/products/force-justdoit-adulto-verdeblanco.png',
    price: 14000,
    size: ['35', '36', '37', '38', '39', '40'],
    color: ['Blanco', 'Turqueza'],
    model: 'Force Just Do It',
  },
  {
    id: 15,
    img: '../donnacalzados/assets/products/force-er-adulto-negroblanco.png',
    price: 13500,
    size: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44'],
    color: ['Blanco', 'Negro'],
    model: 'Force ER',
  },
  {
    id: 16,
    img: '../donnacalzados/assets/products/force-er-adulto-grisblanco.png',
    price: 13500,
    size: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44'],
    color: ['Blanco', 'Gris'],
    model: 'Force ER',
  },
  {
    id: 17,
    img: '../donnacalzados/assets/products/force-er-adulto-grisblanconegro.png',
    price: 13500,
    size: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44'],
    color: ['Blanco', 'Negro', 'Gris'],
    model: 'Force ER',
  },
  {
    id: 18,
    img: '../donnacalzados/assets/products/force-er-adulto-rojoblanconegro.png',
    price: 13500,
    size: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44'],
    color: ['Blanco', 'Negro', 'Rojo'],
    model: 'Force ER',
  },
  {
    id: 19,
    img: '../donnacalzados/assets/products/force-er-adulto-lv.png',
    price: 13500,
    size: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44'],
    color: ['Blanco', 'Negro'],
    model: 'Force ER',
  },
  {
    id: 20,
    img: '../donnacalzados/assets/products/force-er-adulto-lvblanco.png',
    price: 13500,
    size: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44'],
    color: ['Blanco', 'Negro', 'Marron'],
    model: 'Force ER',
  },
  {
    id: 21,
    img: '../donnacalzados/assets/products/force-er-adulto-blanconegro.png',
    price: 13500,
    size: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44'],
    color: ['Blanco', 'Negro'],
    model: 'Force ER',
  },
  {
    id: 22,
    img: '../donnacalzados/assets/products/force-er-adulto-blancorojo.png',
    price: 13500,
    size: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44'],
    color: ['Blanco', 'Rojo'],
    model: 'Force ER',
  },
  {
    id: 23,
    img: '../donnacalzados/assets/products/force-niño-blanco.png',
    price: 9000,
    size: ['27', '28', '29', '30', '31', '32', '33', '34'],
    color: ['Blanco'],
    model: 'Force',
  },
  {
    id: 24,
    img: '../donnacalzados/assets/products/force-niño-blanconegro.png',
    price: 9000,
    size: ['27', '28', '29', '30', '31', '32', '33', '34'],
    color: ['Blanco', 'Negro'],
    model: 'Force Niño',
  },
  {
    id: 25,
    img: '../donnacalzados/assets/products/force-niño-negroblanco.png',
    price: 9000,
    size: ['27', '28', '29', '30', '31', '32', '33', '34'],
    color: ['Blanco', 'Negro'],
    model: 'Force Niño',
  },
  {
    id: 26,
    img: '../donnacalzados/assets/products/force-niño-blancovioleta.png',
    price: 9000,
    size: ['27', '28', '29', '30', '31', '32', '33', '34'],
    color: ['Blanco', 'Violeta'],
    model: 'Force Niño',
  },
];
