export const homeProducts = [
  {
    id: 1,
    img: '../donnacalzados/assets/products/force-adulto-blanco.png',
    title: 'Air Force',
    price: 10500,
    size: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44'],
    category: 'Zapatilla',
    person: ['Hombre', 'Mujer'],
    color: ['Blanco'],
    model: 'Air Force',
  },
  {
    id: 2,
    img: '../donnacalzados/assets/products/force-adulto-rosanegro.png',
    title: 'Air Force',
    price: 10500,
    size: ['35', '36', '37', '38', '39', '40'],
    category: 'Zapatilla',
    person: ['Mujer'],
    color: ['Blanco', 'Negro', 'Rosa'],
    model: 'Air Force',
  },
  {
    id: 3,
    img: '../donnacalzados/assets/products/force-adulto-rosablanco.png',
    title: 'Air Force',
    price: 10500,
    size: ['35', '36', '37', '38', '39', '40'],
    category: 'Zapatilla',
    person: ['Mujer'],
    color: ['Blanco', 'Rosa'],
    model: 'Air Force',
  },
  {
    id: 4,
    img: '../donnacalzados/assets/products/force-adulto-violetablanco.png',
    title: 'Air Force',
    price: 10500,
    size: ['35', '36', '37', '38', '39', '40'],
    category: 'Zapatilla',
    person: ['Mujer'],
    color: ['Blanco', 'Violeta'],
    model: 'Air Force',
  },
  {
    id: 5,
    img: '../donnacalzados/assets/products/force-adulto-blanconegro.png',
    title: 'Air Force',
    price: 10500,
    size: ['35', '36', '37', '38', '39', '40', '41', '42', '43', '44'],
    category: 'Zapatilla',
    person: ['Hombre', 'Mujer'],
    color: ['Blanco', 'Negro'],
    model: 'Air Force',
  },
  {
    id: 6,
    img: '../donnacalzados/assets/products/force-niño-blancovioleta.png',
    title: 'Air Force',
    price: 9000,
    size: ['27', '28', '29', '30', '31', '32', '33', '34'],
    category: 'Zapatilla',
    person: ['Niño'],
    color: ['Blanco', 'Violeta'],
    model: 'Air Force',
  },
  {
    id: 7,
    img: '../donnacalzados/assets/products/force-justdoit-adulto-rosablanco.png',
    title: 'Air Force Just Do It',
    price: 14000,
    size: ['35', '36', '37', '38', '39', '40'],
    category: 'Zapatilla',
    person: ['Mujer'],
    color: ['Blanco', 'Rosa'],
    model: 'Air Force',
  },
  {
    id: 8,
    img: '../donnacalzados/assets/products/force-justdoit-adulto-negroblanco.png',
    title: 'Air Force Just Do It',
    price: 14000,
    size: ['35', '36', '37', '38', '39', '40'],
    category: 'Zapatilla',
    person: ['Hombre', 'Mujer'],
    color: ['Blanco', 'Negro', 'Naranja'],
    model: 'Air Force',
  },
];
