export const productsChild = [
  {
    id: 700,
    img: '../donnacalzados/assets/products/force-niño-blanco.png',
    title: 'Air Force Niño',
    price: 9000,
    size: ['27', '28', '29', '30', '31', '32', '33', '34'],
    category: 'Zapatilla',
    person: ['Niño'],
    color: ['Blanco'],
    model: 'Air Force',
  },
  {
    id: 701,
    img: '../donnacalzados/assets/products/force-niño-blanconegro.png',
    title: 'Air Force Niño',
    price: 9000,
    size: ['27', '28', '29', '30', '31', '32', '33', '34'],
    category: 'Zapatilla',
    person: ['Niño'],
    color: ['Blanco', 'Negro'],
    model: 'Air Force',
  },
  {
    id: 702,
    img: '../donnacalzados/assets/products/force-niño-negroblanco.png',
    title: 'Air Force Niño',
    price: 9000,
    size: ['27', '28', '29', '30', '31', '32', '33', '34'],
    category: 'Zapatilla',
    person: ['Niño'],
    color: ['Blanco', 'Negro'],
    model: 'Air Force',
  },
  {
    id: 703,
    img: '../donnacalzados/assets/products/force-niño-blancovioleta.png',
    title: 'Air Force Niño',
    price: 9000,
    size: ['27', '28', '29', '30', '31', '32', '33', '34'],
    category: 'Zapatilla',
    person: ['Niño'],
    color: ['Blanco', 'Violeta'],
    model: 'Air Force',
  },
];
